name: test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: |
        sudo apt update
        sudo apt install -y make autoconf automake libtool m4 wget gzip bzip2 bison g++ git cmake libtool-bin libtool
    - name: Run a multi-line script
      run: |
        chmod +x ./compile.sh
        ./compile.sh
    - name: Save
      uses: actions/upload-artifact@master
      with:
        name: linux-php-bin
        path: bin
